title: Litian Chen's Homepage
page-top-title: Litian Chen
top-section-bg-text: Economics
home-subtitle: Litian Chen&ensp;|&ensp;陈励天
copyright-text: '&copy; Litian Chen 2023-2025. All Rights Reserved.'
